DROP TABLE IF EXISTS branches;
CREATE TABLE branches (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    country VARCHAR(100) NOT null DEFAULT '',
    city VARCHAR(100) NOT NULL,
    address TEXT NOT NULL,
    mobile VARCHAR(50) NOT null DEFAULT '',
    telephone VARCHAR(50) NOT null DEFAULT '',
    email VARCHAR(255) NOT null DEFAULT '',
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);